### ISSUE TITLE
Permissions to check!

### ISSUE THREAD

**Issue by alexfilipemb98** [mgl23606/JodellePowerMining#1]
Works fine, if you're OP - if not, I cannot bring it to life.
Even though the other players have all possible permissions, they are unable to craft or use the tools. Can you help me with this?

**Comment by Romanoak** [comment]
I am having the same problem. I can use it but no one else can take it out of the crafting table.

**Comment by alexfilipemb98** [comment]
> I am having the same problem. I can use it but no one else can take it out of the crafting table.
To use the permissions better use lucky perms and them

**Comment by mgl23606** [comment]
I made some modifications to the permissions. Could you take a look and check if it's working?

**Comment by alexfilipemb98** [comment]
> I made some modifications to the permissions. Could you take a look and check if it's working?

The permissions, are tricky to use its a good thing to use luck perms to give those permissions to people

**Comment by mgl23606** [comment]
I recommend updating to the latest version before everything.

The permissions need to be set using the permissions.yml file or using a permission manager plugin like simpleperms or lightperms.
